// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: proto/limiter.proto

package limiter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestInput) Reset() {
	*x = RequestInput{}
	mi := &file_proto_limiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInput) ProtoMessage() {}

func (x *RequestInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInput.ProtoReflect.Descriptor instead.
func (*RequestInput) Descriptor() ([]byte, []int) {
	return file_proto_limiter_proto_rawDescGZIP(), []int{0}
}

func (x *RequestInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestInput) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RequestOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOutput) Reset() {
	*x = RequestOutput{}
	mi := &file_proto_limiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOutput) ProtoMessage() {}

func (x *RequestOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOutput.ProtoReflect.Descriptor instead.
func (*RequestOutput) Descriptor() ([]byte, []int) {
	return file_proto_limiter_proto_rawDescGZIP(), []int{1}
}

func (x *RequestOutput) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *RequestOutput) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UsageInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageInput) Reset() {
	*x = UsageInput{}
	mi := &file_proto_limiter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageInput) ProtoMessage() {}

func (x *UsageInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageInput.ProtoReflect.Descriptor instead.
func (*UsageInput) Descriptor() ([]byte, []int) {
	return file_proto_limiter_proto_rawDescGZIP(), []int{2}
}

func (x *UsageInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UsageOutput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestsAllowed int32                  `protobuf:"varint,1,opt,name=requests_allowed,json=requestsAllowed,proto3" json:"requests_allowed,omitempty"`
	RequestsUsed    int32                  `protobuf:"varint,2,opt,name=requests_used,json=requestsUsed,proto3" json:"requests_used,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UsageOutput) Reset() {
	*x = UsageOutput{}
	mi := &file_proto_limiter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageOutput) ProtoMessage() {}

func (x *UsageOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageOutput.ProtoReflect.Descriptor instead.
func (*UsageOutput) Descriptor() ([]byte, []int) {
	return file_proto_limiter_proto_rawDescGZIP(), []int{3}
}

func (x *UsageOutput) GetRequestsAllowed() int32 {
	if x != nil {
		return x.RequestsAllowed
	}
	return 0
}

func (x *UsageOutput) GetRequestsUsed() int32 {
	if x != nil {
		return x.RequestsUsed
	}
	return 0
}

var File_proto_limiter_proto protoreflect.FileDescriptor

const file_proto_limiter_proto_rawDesc = "" +
	"\n" +
	"\x13proto/limiter.proto\x12\alimiter\";\n" +
	"\fRequestInput\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"A\n" +
	"\rRequestOutput\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"%\n" +
	"\n" +
	"UsageInput\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"]\n" +
	"\vUsageOutput\x12)\n" +
	"\x10requests_allowed\x18\x01 \x01(\x05R\x0frequestsAllowed\x12#\n" +
	"\rrequests_used\x18\x02 \x01(\x05R\frequestsUsed2\x83\x01\n" +
	"\vRateLimiter\x12=\n" +
	"\fAllowRequest\x12\x15.limiter.RequestInput\x1a\x16.limiter.RequestOutput\x125\n" +
	"\bGetUsage\x12\x13.limiter.UsageInput\x1a\x14.limiter.UsageOutputB\x10Z\x0e/proto;limiterb\x06proto3"

var (
	file_proto_limiter_proto_rawDescOnce sync.Once
	file_proto_limiter_proto_rawDescData []byte
)

func file_proto_limiter_proto_rawDescGZIP() []byte {
	file_proto_limiter_proto_rawDescOnce.Do(func() {
		file_proto_limiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_limiter_proto_rawDesc), len(file_proto_limiter_proto_rawDesc)))
	})
	return file_proto_limiter_proto_rawDescData
}

var file_proto_limiter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_limiter_proto_goTypes = []any{
	(*RequestInput)(nil),  // 0: limiter.RequestInput
	(*RequestOutput)(nil), // 1: limiter.RequestOutput
	(*UsageInput)(nil),    // 2: limiter.UsageInput
	(*UsageOutput)(nil),   // 3: limiter.UsageOutput
}
var file_proto_limiter_proto_depIdxs = []int32{
	0, // 0: limiter.RateLimiter.AllowRequest:input_type -> limiter.RequestInput
	2, // 1: limiter.RateLimiter.GetUsage:input_type -> limiter.UsageInput
	1, // 2: limiter.RateLimiter.AllowRequest:output_type -> limiter.RequestOutput
	3, // 3: limiter.RateLimiter.GetUsage:output_type -> limiter.UsageOutput
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_limiter_proto_init() }
func file_proto_limiter_proto_init() {
	if File_proto_limiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_limiter_proto_rawDesc), len(file_proto_limiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_limiter_proto_goTypes,
		DependencyIndexes: file_proto_limiter_proto_depIdxs,
		MessageInfos:      file_proto_limiter_proto_msgTypes,
	}.Build()
	File_proto_limiter_proto = out.File
	file_proto_limiter_proto_goTypes = nil
	file_proto_limiter_proto_depIdxs = nil
}
